aFORMAT: 1A
HOST: http://polls.apiblueprint.org/

# mynewtestapi

Polls is a simple API allowing consumers to view polls and vote in them.

## book collection [/books]

### List All books [GET]

+ Response 200 (application/json; charset=utf-8)

        [
           {
              "book_id" : 123,
              "book_name" : "worldwar"
           }
        ]