aFORMAT: 1A
HOST: http://polls.apiblueprint.org/

# mynewtestapi

My new api

## Book collection [/books]

### Get All books [GET /books]

 + Response 200 (application/json; charset=utf-8)
   + Attributes (fixed-type)
     - books (array[Book], fixed-type)

### Get history books [GET /books/{id}?type=history]

  + Parameter
    + id : 1 (number) - ID of book

  + Response 200 (application/json; charset=utf-8)
     + Attributes (fixed-type)
       - Include Book 
       - bookdetail (array[BookDetails], fixed-type)
       - book_size: 4343 (number)

       
### Get fiction books [GET /books/{id}?type=fiction]

  + Parameter
    + id : 1 (number) - ID of book

  + Response 200 (application/json; charset=utf-8)
     + Attributes (fixed-type)
       - Include Book 
       - bookdetail (array[BookDetails], fixed-type)
       - book_lenght: 556 (number)


# Data structure

## Book (object, fixed)
+ book_pages : 200 (number)
+ book_name  : worldwar2 (string)
+ book_shop : shop1 (string)
+ book_color : black (string)
 
## BookDetails (object, fixed)
+ book_size : '43' (string)