aFORMAT: 1A
HOST: http://polls.apiblueprint.org/

# mynewtestapi

My new api

## Book collection [/books]

### Get All books [GET /books]

 + Response 200 (application/json)
   + Attributes (fixed-type)
     - books (array[Book])

### Get one books [GET /books/{id}]

 + Parameter
   + id : 1 (number) - ID of book
   
 + Response 200 (application/json)
   + Attributes (fixed-type)
     - Include Book 
     - bookdetail (array[BookDetails])
     - book_size 4343 (number)
   

# Data structure

## Book (object)
+ book_pages : 200 (number)
+ book_name  : worldwar2 (string)
+ book_shop : shop1 (string)
+ book_color : black (string)
 
## BookDetails (object)
+ book_size : '43' (string)